<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'libphonenumber' => array($vendorDir . '/giggsey/libphonenumber-for-php/src'),
    'Valitron' => array($vendorDir . '/vlucas/valitron/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
);
