<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitcc318394eace8d462afb0f0636970fc0
{
    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'PingYo\\' => 7,
        ),
        'B' =>
            array (
                'BizFellaUSA\\' => 7,
            ),
        'U' =>
            array (
                'UPing\\' => 7,
            ),
        'M' =>
        array (
            'Monolog\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PingYo\\' =>
        array (
            0 => __DIR__ . '/../..',
            1 => __DIR__ . '/..' . '/papersky/pingyo/src',
            2 => __DIR__ . '/..' . '/papersky/bizfellausa/src',
            3 => __DIR__ . '/..' . '/papersky/uping/src',
        ),
        'Monolog\\' =>
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
    );

    public static $prefixesPsr0 = array (
        'l' =>
        array (
            'libphonenumber' =>
            array (
                0 => __DIR__ . '/..' . '/giggsey/libphonenumber-for-php/src',
            ),
        ),
        'V' =>
        array (
            'Valitron' =>
            array (
                0 => __DIR__ . '/..' . '/vlucas/valitron/src',
            ),
        ),
        'P' =>
        array (
            'Psr\\Log\\' =>
            array (
                0 => __DIR__ . '/..' . '/psr/log',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitcc318394eace8d462afb0f0636970fc0::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitcc318394eace8d462afb0f0636970fc0::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitcc318394eace8d462afb0f0636970fc0::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
