<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'PingYo\\' => array($baseDir . '/PingYo', $vendorDir . '/papersky/pingyo/src'),
    'BizFellaUSA\\' => array($baseDir . '/BizFellaUSA', $vendorDir . '/papersky/bizfellausa/src'),
    'UPing\\' => array($baseDir . '/UPing', $vendorDir . '/papersky/uping/src'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
);
